# Copyright 2015-2016 Harri Kapanen <harri.kapanen@iki.fi>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
# Run setup first, then
# export ANSIBLE_VAULT_PASSWORD_FILE=<file>
# ./provision.sh 192.168.1.100 playbooks/tkurki/cassiopeia.yml

- hosts: all
  remote_user: pi
  gather_facts: yes
  become: yes

  vars:
    - hostname: cassiopeia
    - timezone: Europe/Helsinki

  vars_files:
    - secrets.yml

  roles:
    - common
    - role: huawei_e3372h
    - role: upnpc
      upnpc_interface: eth1
      upnpc_port_forwards: "500 UDP 4500 UDP 1701 UDP"
      upnpc_port_redirects:
        - "192.168.8.100 22 2222 tcp"
    - l2tp_vpn_server
    - hotspot
    - role: nat_router
      nat_router_fw_input_rules:
        - "-A FORWARD -i eth1 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT"
        - "-A FORWARD -i wlan0 -o eth1 -j ACCEPT"
        - "-A FORWARD -i eth1 -o eth0 -m state --state RELATED,ESTABLISHED -j ACCEPT"
        - "-A FORWARD -i eth0 -o eth1 -j ACCEPT"
      nat_router_inet_interface: eth1
    # deprecated, use signalk-npm instead
    # - role: signalk
    #   node_app_env:
    #     - "NODE_ENV=production"
    #     - "SIGNALK_NODE_SETTINGS=/home/pi/cassiopeia-settings/signalk-server-settings.json"
    - route53-ddns

  tasks:
    - lineinfile: dest=/etc/udev/rules.d/99-cassiopeia-usb-devices.rules create=yes line="SUBSYSTEM==\"tty\", ACTION==\"add\", ATTRS{serial}==\"FTUL7DTY\", SYMLINK+=\"nmea-digyacht\""
    - lineinfile: dest=/etc/udev/rules.d/99-cassiopeia-usb-devices.rules line="SUBSYSTEM==\"tty\", ACTION==\"add\", ATTRS{serial}==\"FTUL7DTY\", GROUP=\"pi\""
    - lineinfile: dest=/etc/udev/rules.d/99-cassiopeia-usb-devices.rules line="SUBSYSTEM==\"tty\", ACTION==\"add\", ATTRS{serial}==\"A901IPKN\", SYMLINK+=\"nmea-dxt\""
    - lineinfile: dest=/etc/udev/rules.d/99-cassiopeia-usb-devices.rules line="SUBSYSTEM==\"tty\", ACTION==\"add\", ATTRS{serial}==\"A901IPKN\", GROUP=\"pi\""
    - lineinfile: dest=/etc/udev/rules.d/99-cassiopeia-usb-devices.rules line="SUBSYSTEM==\"tty\", ACTION==\"add\", ATTRS{serial}==\"1FD34\", SYMLINK+=\"actisense\""
    - lineinfile: dest=/etc/udev/rules.d/99-cassiopeia-usb-devices.rules line="SUBSYSTEM==\"tty\", ACTION==\"add\", ATTRS{serial}==\"1FD34\", GROUP=\"pi\""
    - name: Pull own settings from the repository
      git: repo=https://github.com/tkurki/cassiopeia-settings dest=/home/pi/cassiopeia-settings force=yes version=master
    - name: Install own providers
      command: npm install tkurki/cassiopeia-providers
      args:
        chdir: /opt/signalk-server
    - name: Restart signalk-server
      service: name=signalk-server state=restarted
      become: true

  handlers:
    - include: ../../handlers/handlers.yml
