---
- name: S/Y Curiosity Onboard Computer
  hosts: all
  remote_user: pi
  gather_facts: yes
  become: yes

  vars:
    - hostname: curiosity-pi
    - timezone: Etc/UTC


  roles:
    - role: common
    - role: signalk
      signalk_plugins:
      - plugin_name: "@signalk/charts-plugin"
      - plugin_name: "gpxload"
      - plugin_name: "signalk-anchoralarm-plugin"
      - plugin_name: "signalk-simple-notifications"
      - plugin_name: "signalk-push-notifications"
      - plugin_name: "signalk-alarm-silencer"
      - plugin_name: "signalk-wilhelmsk-plugin"
      - plugin_name: "signalk-raspberry-pi-bme280"
      - plugin_name: "signalk-raspberry-pi-temperature"
      - plugin_name: "@meri-imperiumi/signalk-aws-iot"

  tasks:
    - name: Deploy SSH keys for bergie
      authorized_key:
        user: pi
        state: present
        key: https://github.com/bergie.keys
    - name: Deploy SSH keys for cannonerd
      authorized_key:
        user: pi
        state: present
        key: https://github.com/cannonerd.keys
    - name: Pull boat settings from GitHub
      git:
        repo: https://github.com/meri-imperiumi/curiosity.git
        dest: /home/pi/curiosity
      become: no
    - name: Copy Signal K settings file
      copy:
        src: /home/pi/curiosity/signalk/settings.json
        dest: /home/pi/.signalk/settings.json
        remote_src: yes
      become: no
    - name: Copy Signal K defaults file
      copy:
        src: /home/pi/curiosity/signalk/defaults.json
        dest: /home/pi/.signalk/defaults.json
        remote_src: yes
      become: no
    - name: Synchronize two directories on one remote host.
      synchronize:
        src: /home/pi/curiosity/signalk/plugin-config-data
        dest: /home/pi/.signalk
      delegate_to: "{{ inventory_hostname }}"
      become: no
    - name: Restart signalk-server
      service:
        name: signalk-server
        state: restarted

  handlers:
    - include: ../../handlers/handlers.yml
