# Copyright 2016 Teppo Kurki <teppo.kurki@iki.fi>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
---
  - name: "Install mdns dependency"
    apt: pkg=libavahi-compat-libdnssd-dev state=latest

  - name: Copy custom SignalK server defaults
    copy:
      src: "{{ signalk_defaults_file }}"
      dest: "/home/{{ node_app_user }}/.signalk/defaults.json"
      mode: 0644
    become_user: "{{ node_app_user }}"
    when: signalk_defaults_file is defined
    notify: restart-signalk-server

  - name: Copy Custom SignalK server settings
    copy:
      src: "{{ signalk_settings_file }}"
      dest: "/home/{{ node_app_user }}/.signalk/settings.json"
      mode: 0644
    become_user: "{{ node_app_user }}"
    when: signalk_settings_file is defined
    notify: restart-signalk-server

  - name: Install SignalK server plugins
    include:
      file: install_plugin.yml
      plugin_name: "{{ item.plugin_name | default(item) }}"
      plugin_config_src: "{{ item.plugin_config_src | default('') }}"
      plugin_config_dst: "{{ item.plugin_config_dst | default('') }}"
    with_items: "{{ signalk_plugins }}"
    when: signalk_plugins is defined
